### ISSUE TITLE
Crazy Craft Legasy does not want to run

### ISSUE THREAD

**Issue by CiMy69** [Voidswrath-Support/Bug-reports#12]
Every time I want to enter the game, it starts loading and after a few seconds it writes 1.6.4 not responding and returns me to the desktop. I'm sorry to bother you. Thank you for read this.
![image_2020-11-12_002901](https://user-images.githubusercontent.com/74330557/98876210-10b97180-247e-11eb-9fbb-bb927e1625c9.png)

**Comment by DoctorBang** [comment]
Fill out the issue form please
