### ISSUE TITLE
Dimensions portals are glitched

### ISSUE THREAD

**Issue by sunboarder** [Voidswrath-Support/Bug-reports#3]
**Describe the bug**
When i wanna go trough a portal like for the red ant dimension i want to go trough i just get teleported to the air and im just falling down.... and if i do get through then the dimension lags out like crazy..

**Steps to reproduce**
How to reproduce the bug goes here. 
For example:
Step 1: Click ...
Step 2: Punch ...

**Expected Behavior**
Please state what you expected to happen when you performed these actions.

**Screenshots**
If you have any screenshots that are applicable, please post them here.

<details>
  <summary><strong>Game Output</strong></summary>

```

```
</details>

<details>
  <summary><strong>Crash Report</strong></summary>

```

```
</details>

<details>
  <summary><strong>Additional Information</strong></summary>

- Launcher bug [Y/N]: 
- Modpack: 
- Additional mods: 
- Operating system: 

</details>

**Additional Information**
List any additional information you wish to provide.

**Comment by DoctorBang** [comment]
@sunboarder Can you try turning off random dimensions and seeing if that fixes it?

**Comment by DoctorBang** [comment]
Aight, I assume that this was a result of random dimensions. Closing issue.

**Comment by sunboarder** [comment]
Suddenly it started working again so its fixed
Op zo 13 sep. 2020 om 02:35 schreef DoctorBang <notifications@github.com>
