### ISSUE TITLE
Nether bug + ant bug

### ISSUE THREAD

**Issue by itstrickkzz** [Voidswrath-Support/Bug-reports#4]
Whenever i jump into the nether portal it just teleports me to the overworld but really high......., and if i click one of the ants of orespawn i just run on 7 fps i cant do anything i opened up 8gb of ram on launcher en 5gb on my server and cant seem to fix it..... pls help

**Comment by DoctorBang** [comment]
@itstrickkzz  Can you try turning off random dimensions?

**Comment by itstrickkzz** [comment]
Okay but how…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Richcool1** [comment]
Hit window button + R, type %appdata%, go to .crazycraft4 folder then go to config folder then recipe scramble folder then recipe scramble file.

**Comment by DoctorBang** [comment]
Also @itstrickkzz I deleted your comment because you leaked your email in it

**Comment by DoctorBang** [comment]
Fixed on discord it seems.
